### PR TITLE
Ensure _super wrap is only called for setter if present

### LINKED ISSUE #27: Function.prototype.toString requires that 'this' be a Function
This error is thrown when a readonly CP overrides a CP with setter (defined on the parent class). Seems to be introduced by #18. Working on a PR...

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #27

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good to me!

**Comment by simonihmig** [comment]
@pzuraq would you be to have a quick look at this?

**Review by pzuraq — APPROVED** [review]

**Comment by pzuraq** [comment]
Published in v1.1.2

**Comment by simonihmig** [comment]
Thank you! ❤️

**Pull request merged**
